# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.synced_folder "/Users/gopass2002/Lavender", "/home/lavender/lavender", disabled: false, owner: "lavender", group: "lavender"
    config.vm.synced_folder "/Users/gopass2002/virtualenvs/lavender", "/home/lavender/env", disabled: false, owner: "lavender", group: "lavender"
    config.vm.provision "shell", path: "provision.sh"

    config.vm.define :master do |node|
        node.vm.hostname = 'master'
        node.vm.network "public_network", ip: "192.168.20.200"
        node.vm.network "public_network", bridge: 'en6'
        node.ssh.insert_key = 'true'
    end

    config.vm.define :slave1 do |node|
        node.vm.hostname = 'slave1'
        node.vm.network "public_network", ip: "192.168.20.201"
        node.vm.network "public_network", bridge: 'en6'
    end

    config.vm.define :slave2 do |node|
        node.vm.hostname = 'slave2'
        node.vm.network "public_network", ip: "192.168.20.202"
        node.vm.network "public_network", bridge: 'en6'
    end

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "8192"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
end
