# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = 'ubuntu-dev'
    config.vm.synced_folder "~/workspace", "/workspace", disabled: false, owner: "ubuntu-dev", group: "ubuntu-dev"
    config.vm.synced_folder "~/virtualenv", "/virtualenv", disabled: false, owner: "ubuntu-dev", group: "ubuntu-dev"
    config.vm.network "public_network", bridge: 'en4: Thunderbolt', ip: "192.168.20.100"

    config.vm.provision "shell", path: "provision.sh"

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "10240"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
end
