# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "chef/centos-6.5"

    config.vm.define :master do |node|
        node.vm.hostname = 'master'
        node.vm.network "public_network", ip: "192.168.20.210"
        node.vm.network "public_network", bridge: 'en6'
        node.ssh.insert_key = 'true'
    end

    config.vm.define :slave1 do |node|
        node.vm.hostname = 'slave1'
        node.vm.network "public_network", ip: "192.168.20.211"
        node.vm.network "public_network", bridge: 'en6'
    end

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
end
